backend:
  name: git-gateway
  repo: mauriciabad/digital-menu-escastell
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

locale: 'es'
site_url: https://escastell-carta.netlify.app/

media_folder: static/img
public_folder: /img

collections:
  - name: "menu"
    label: "Carta"
    folder: "src/pages"
    create: true
    slug: "{{fields.lang.langCode}}"
    identifier_field: "lang.langName"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "menu-post"}
      - label: "Idioma"
        name: "lang"
        widget: "object"
        collapsed: true
        fields: 
        - {label: "Código de idioma (ISO 639-1)", name: "langCode", widget: "string", pattern: ['^[a-z]{2}$', 'Código de idioma incorrecto']}
        - {label: "Nombre (en el propio idioma)", name: "langName", widget: "string"}
        - {label: "Bandera", name: "langImage", widget: image}
      - {label: "Contenido", name: "body", widget: "markdown"}
  # - name: "settings"
  #   label: "Configuración"
  #   create: false
  #   editor:
  #     preview: false
  #   files:
  #     - file: "src/settings.md"
  #       label: "General"
  #       name: "settings"
  #       fields:
  #         - {label: "Template Key", name: "templateKey", widget: "hidden", default: "settings"}
  #         - {label: "Fondo", name: "bgimage", widget: image}
  #         - {label: "Código del idioma predeterminado", name: "defaultLang", widget: "string", pattern: ['^[a-z]{2}$', 'Código de idioma incorrecto']}
  #         - label: "Redes sociales"
  #           name: "social"
  #           widget: "object"
  #           collapsed: false
  #           fields: 
  #           - {label: "Web (URL)", name: "socialWeb", widget: "string"}
  #           - {label: "Facebook (URL)", name: "socialFacebook", widget: "string"}
  #           - {label: "Twitter (URL)", name: "socialTwitter", widget: "string"}
  #           - {label: "Instagram (URL)", name: "socialInstagram", widget: "string"}
